--- 
- hosts: all 
  become: yes 
  tasks: 
  - name: i want to install webserver 
    apt: 
     name: apache2
     state: present  

  - name: i want to install tree 
    apt: 
     name: tree 
     state: present 

  - name: install webserver on RedHat nodes 
    yum: 
     name: httpd
     state: present 
    when: ansible_os_family =="RedHat" 

  - name: i want start webserver on RedHat nodes 
    server: 
      name: httpd 
      start: started 
    when: ansible_os_family=="RedHat"     
    
